image: python:3.7.4-alpine3.10

definitions:
  services: 
    docker: 
      # Memory docker-in-docker 
      memory: 3072

pipelines:
  branches:
      master:
      - step:
          services:
            - docker
          size: 2x
          caches:
            - pip
          script:
            - pip3 install awscli
            - pip3 install envsubst
            - IMAGE="${ACCOUNT_NUMBER_DEV}.dkr.ecr.us-east-1.amazonaws.com/credenti-admin-portal"
            - TAG="${BITBUCKET_BUILD_NUMBER}"
            - touch .env.local
            - echo "DISABLE_ESLINT_PLUGIN=true" | cat >> .env.local
            - docker build -t $IMAGE:$TAG .
            - aws configure set aws_access_key_id "${AWS_ACCESS_KEY_DEV}"
            - aws configure set aws_secret_access_key "${AWS_SECRET_ACCESS_KEY_DEV}"
            - eval $(aws ecr get-login --no-include-email --region us-east-1 | sed 's;https://;;g')
            - docker push $IMAGE:$TAG
            - export BUILD_NUMBER="${BITBUCKET_BUILD_NUMBER}"
            - export ACCOUNT_NUMBER="${ACCOUNT_NUMBER_DEV}"
            - envsubst <deployment.yml >credenti-deployment.yaml
            - pipe: atlassian/aws-eks-kubectl-run:2.2.0
              variables:
                AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_DEV}
                AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY_DEV}
                AWS_DEFAULT_REGION: "us-east-1"
                CLUSTER_NAME: ${AWS_CLUSTER_DEV}
                KUBECTL_COMMAND: "apply"
                RESOURCE_PATH: "credenti-deployment.yaml"
                DEBUG: "true"
            
            